autocmd BufEnter *.pc set filetype=esqlc
map P :!man 3 iskeyword<CR>
set path=.,/usr/local/include,/usr/include
:map gf :e <cfile><CR>

"vi cmd
fc  	Move forward to c 	Fc	Move back to c

mc	Set marker c on this line	 `c	Go to beginning of marker c line. 	'c	Go to first non-blank character of marker c line

/[0-9]\{2\}

~	Toggle upp and lower case	

.	Repeat last text-changing command

:nr 	fileReads file and inserts it after line n
l/se list 	tab (^l) backslash (\) backspace (^H) newline ($) bell (^G) formfeed (^L^)

n|	Moves to the column n in the current line
:reg	vim粘贴板 "1yy

&	Repeats last :s command
:g/str/cmd	Runs cmd on all lines that contain str
:g/str1/s/str2/str3/	Finds the line containing str1, replaces str2 with str3
:n,ms/str1/str2/opt	Searches from n to m for str1; replaces str1 to str2; using opt-opt can be g for global change, c to confirm change (y to acknowledge, to suppress), and p to print changed lines
:v/str/cmd 	Executes cmd on all lines that do not match str
!! cmd	Executes shell command cmd, places output in file starting at current line
!! ctrl+r reg_no backspace
:r! cmd	Reads and inserts output from cmd
:f filename	rename
:cd 	dirChanges current working directory to dir 
:sh	Starts a sub-shell (CTRL-d returns to editor) 
:so 	fileReads and executes commands in file (file is a shell script)
!}sort args	Sorts from current position to end of paragraph and replaces text with sorted text
“ny
q: 	show history cmd
gd/*/#	partern current word
:set all

