CREATE DATABASE TEST2
USER SYS IDENTIFIED BY The_sunqi
USER SYSTEM IDENTIFIED BY The_sunqi
CONTROLFILE REUSE
LOGFILE GROUP 1 ('/oracle/app/oradata/TEST2/redo01.log') SIZE 100M,
GROUP 2 ('/oracle/app/oradata/TEST2/redo02.log') SIZE 100M,
GROUP 3 ('/oracle/app/oradata/TEST2/redo03.log') SIZE 100M
MAXLOGFILES 5
MAXLOGMEMBERS 5
MAXLOGHISTORY 1
MAXDATAFILES 100
MAXINSTANCES 1
CHARACTER SET ZHS16GBK
NATIONAL CHARACTER SET AL16UTF16
EXTENT MANAGEMENT LOCAL
DATAFILE '/oracle/app/oradata/TEST2/system01.dbf' SIZE 325M REUSE
SYSAUX DATAFILE '/oracle/app/oradata/TEST2/sysaux01.dbf' SIZE 325M REUSE
DEFAULT TABLESPACE tbs_1
DATAFILE '/oracle/app/oradata/TEST2/tbs_1.dbf'  size 100M REUSE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
DEFAULT TEMPORARY TABLESPACE tempts1
TEMPFILE '/oracle/app/oradata/TEST2/temp01.dbf'
SIZE 20M REUSE
UNDO TABLESPACE UNDOTBS1
DATAFILE '/oracle/app/oradata/TEST2/undotbs01.dbf'
SIZE 200M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
